export const ROUTES = {
  HOME: "/",
  ABOUT_US: "/about",
  MISSION_VISION: "/mission-vision",
  ABOUT_YCB: "/about-ycb",
  ABOUT_AYUSH: "/about-ayush",
  REGISTRATION_FORM: "/registration",
  PRE_MEDICAL_FORM: "/pre-medical",
  RESULT: "/result",
  COMPLAINTS_APPEALS: "/complaintsAndAppeals",
  GALLERY: "/gallery",
  VIDEOS: "/videos",
  NEWS: "/news",
  ENVIRONMENT: "/environment",
  BENEFITS: "/benefits",
  FAQS: "/faqs",
  YT_SYLLABUS: "/demo",
  CANDIDATES:"/candidate",
  YOGA_GOALS:"/yoga-goals",
  PRIVACY_POLICY:"/privacy-policy",
  TERMS_CONDITIONS:"/terms-conditions"
};